
name: alpine-php8-lumen

on: [push]

env:
  IMAGE_NAME: ${{ github.workflow	}}
  GITHUB_USER: burnett01
  DOCKER_USER: burnett0

jobs:

  build-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: | 
          docker build . --file Dockerfile --tag image
      - name: Log into Github Docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ env.GITHUB_USER }} --password-stdin
        
      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ env.GITHUB_USER }}/docker-images/${{ env.IMAGE_NAME }}
          docker tag image $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
        
      - name: Log into Docker registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.io -u ${{ env.DOCKER_USER }} --password-stdin
        
      - name: Push image
        run: |
          IMAGE_ID=docker.io/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}
          docker tag image $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
