name: php7-3-cli-ext-mysql

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:

  push:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io/burnett0/php7-3-cli-ext-mysql
          repository: burnett0/php7-3-cli-ext-mysql
          file: php7-3-cli-ext-mysql/Dockerfile

 
